name: "sketch_generate"
backend: "python"
max_batch_size: 1

input [
  {
    name: "preprocessed_data"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  },
  {
    name: "person_id"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  },
  {
    name: "status"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  }
]

output [
  {
    name: "scene_images"
    data_type: TYPE_BYTES
    dims: [ -1 ]
  },
  {
    name: "scene_names"
    data_type: TYPE_BYTES
    dims: [ -1 ]
  },
  {
    name: "person_id"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  },
  {
    name: "status"
    data_type: TYPE_BYTES
    dims: [ 1 ]
  }
]

instance_group [
  {
    kind: KIND_GPU
    gpus: [ 0 ]
    count: 1
  }
]
